### PR TITLE
Check if a first post exists

### PR DESCRIPTION
**Pull request by markwooff**
Fix for https://github.com/gctools-outilsgc/gccollab/issues/276

### CODE REVIEW

**Comment by markwooff** [comment]
@ethanWallace just added some checks into your streaming content JS files. Also changed the selector since it was causing issues with Wire Post re-shares (see https://github.com/gctools-outilsgc/gccollab/issues/276).

**Comment by ethanWallace** [comment]
@markwooff I tested this on my local and the wire and the department activity pages are working correctly. On the community pages the wire widget in the sidebar is working correctly but the main newsfeed seems to constantly think there is a new post. And finally the News Feed page doesn't seem to work anymore. I checked to see what was wrong and it seems like it cant find any new posts.

**Comment by markwooff** [comment]
Thanks for the comments @ethanWallace . The selector I had used for the newsfeed wasn't always valid so I've replaced it with one that should work regardless of the content type being displayed.

I'm not sure why the community newsfeed is constantly thinking there is a new post, all I've added was an if statement to ensure a post exists from the selector. Plus we don't have this feature on GCcollab to test with. Any ideas?

**Comment by ethanWallace** [comment]
@markwooff I will take a look to see why the community newsfeed is acting strange.

**Pull request merged**
