### PR TITLE
chore: add EditorConfig for whitespace consistency

### PR DESCRIPTION
**Pull request by nschonni**
Opened an upstream issue for this but haven't heard back https://github.com/Elgg/Elgg/issues/10973

### CODE REVIEW

**Comment by nschonni** [comment]
@pandurx this might help some of your formatting cleanup

**Comment by nschonni** [comment]
Many IDEs have direct support now and for those that don't there are plug-ins http://editorconfig.org/#download

**Comment by nschonni** [comment]
> Is Travis also checking formatting?

Upstream has some stuff, but I don't believe it is setup for all the mods that have been added here.
This will also work with the GitHub web editor

**Comment by pandurx** [comment]
been drowning in an endless sea of issues ...blah
I'm not sure how I would be able to test this, but this should support the editors that we are currently using (Sublime Text 2, Vim, and maybe nano)

**Pull request merged**
