### PR TITLE
Wire Message + Images (notifications)

### PR DESCRIPTION
**Pull request by pandurx**
This Pull request is for Issue #1640 
Also relates to https://github.com/gctools-outilsgc/gcconnex/pull/1585

### CODE REVIEW

**Comment by pandurx** [comment]
@Steph4104 are you able to reply to a wire post with the image upload? my instance stalls for a little bit then it doesn't do anything more

**Comment by Steph4104** [comment]
@markwooff and @ethanWallace  can you take a look at the refresh problem?

**Comment by GCDevExchange-CarrefourProgGC** [comment]
@Steph4104 what's the issue? Assuming it's related to the streaming portion that @ethanWallace built?

**Comment by markwooff** [comment]
@Steph4104 what's the issue? Assuming it's related to the streaming portion that @ethanWallace built?

**Comment by Steph4104** [comment]
@markwooff the one Christine talk two comment before. "The post is saved but the page needs to be manually refreshed to see the new post." 

When you test on preprod, you can post but you have to manually close the modal and refresh the page to see it.

**Comment by markwooff** [comment]
Ah okay, I'll take a look at it. Thanks @Steph4104

**Comment by markwooff** [comment]
@Steph4104 issue should now be fixed!

**Pull request merged**
