### PR TITLE
more changes for gcdirectory sync

### PR DESCRIPTION
**Pull request by Troy-Lawson**
yet more changes...

### CODE REVIEW

**Comment by Troy-Lawson** [comment]
this is not on preprod. please just accept or approve or whatever. thanks

**Comment by LemieuxGen** [comment]
@Troy-Lawson looked at the code, language seems ok. Will this fix the My colleagues link (left of user profile card), button text (removing "le"), etc. in the emails? seems to be missing a few things, but I may not have seen everything in the code. Thanks.

**Comment by Troy-Lawson** [comment]
@LemieuxGen several of those things have already been fixed in production. Several of the issues were because the language files were being overwritten in the translation editor. everything should say just "my colleagues" again (including the access options, but that will be addressed in the code above)

**Comment by LemieuxGen** [comment]
@Troy-Lawson, ok, thanks. One clarification, the access level (privacy settings) should say "My colleagues on GCconnex only" (FR: Mes collègues sur GCconnex seulement).
As per email: o	Access levels should be “Only me”, “My colleagues on GCconnex”, “All public servants” / “Seulement moi”, “Mes collègues sur GCcollègues”, “Tous les fonctionnaires”

Others links to access list of colleagues on GCconnex should say "My colleagues" (Mes collègues).

my colleagues link
my colleagues link_2

**Comment by Troy-Lawson** [comment]
correct. that change has been made and is in the files in this pull request

**Pull request merged**
