### PR TITLE
fix extra wide site menus forcing a horizontal scroll bar on most pages

### PR DESCRIPTION
**Pull request by Phanoix**

### CODE REVIEW

**Review by piet0024 — COMMENTED** [review]
This looks good to me on the test site and from the code side. Let's get a quick review from @AdiMakkar to confirm and it should be good to go!

**Comment by AdiMakkar** [comment]
Looks good to me for the scroll bar issue. I would like to change some css edits in the search collapse function as well, if @piet0024 or @Phanoix can review that as well, we can merge it.

**Comment by AdiMakkar** [comment]
Added search collapse design changes: 
1. Removed border outline at the top of collapse box 
2. Added margin-top for a cleaner and slick menu

**Review by AdiMakkar — APPROVED** [review]
Happy with the scroll bar changes, pending @Phanoix or @piet0024's approval for the design changes

**Pull request merged**
