### PR TITLE
Some notifications fixes

### PR DESCRIPTION
**Pull request by pandurx**
Re-using the notification-fixes branch (see commits after 4514309)

### CODE REVIEW

**Comment by klecuyer** [comment]
Notifications are still not sending when I post a blog or file to a group. Users have reported this and I have tested myself in the Sandbox testing group.
https://gcconnex.gc.ca/blog/view/29581794/ennotifications-on-a-blog-againfr

**Comment by klecuyer** [comment]
GCconnex got the notification. My subscribed personal account did not. Also, the 'Do not send a notification' button still sends a notification when checked.

**Comment by pandurx** [comment]
@nschonni that's a good idea, to have some important functions listed or documented somewhere (since it is apparently used in almost every plugin)

**Comment by pandurx** [comment]
@klecuyer 

i got the email notification for https://gcconnex.gc.ca/blog/view/29581794/ennotifications-on-a-blog-againfr (this issue seems sporadic, and only sends if it wants to send)

the "do not send a notification" has been resolved, but it is not pushed to production yet

**Comment by klecuyer** [comment]
I can confirm that this group (as well as others) is still experiencing major notification bugs as of today. 
https://gcconnex.gc.ca/groups/profile/19651377/enexecutive-corner-carrefour-des-cadres-supu00e9rieursfr

Despite multiple users being subscribed to notifications from this group (and not to the Digest) when a new blog is posted, users are not getting a notification (group of 900+ members). I can log into multiple members' accounts and see no signs of notifications from the blog post. As a workaround, the author is emailing all group members, and after Sending once, the members' are all consistently receiving 4 notifications of the message/email and still none from the original blog post. 

4x notification bug posted here: #1352

**Pull request merged**
