### PR TITLE
change to splash page so site uses single language cookie

### PR DESCRIPTION
**Pull request by Troy-Lawson**

### CODE REVIEW

**Comment by pandurx** [comment]
I'm testing this on my local on IE11 because Chrome does something special with cookie management. The cookie doesn't seem to be retaining the new changes (I console.log the string and commented out `parent.location.href=frenchlink` so it doesn't clear my log):

`document.cookie = name + "=" +escape( value ) + ";path=/" + ";expires=" + expires_date.toGMTString() + ";domain=$domain";`

I keep getting:

`Cookie: Elgg=62mlgc2co74l1ho8oall7b9h40`

**Comment by Troy-Lawson** [comment]
@pandurx tagging so you see reply

**Comment by pandurx** [comment]
The logic in the code is perfectly fine, but the browser on my machine might behave differently compared to Preprod/Prod

**Comment by Troy-Lawson** [comment]
@pandurx i dont know if it has been pushed to pre-prod if that is where you are testing it

**Pull request merged**
