### PR TITLE
Hackathon Team NOP

### LINKED ISSUE #811: Correction to french title / links in "My Colleagues"
When language selection is set to French;
The Title of this section is displayed as "Kevin Chagnon' mes collègues" - should be something in the likes of "Les collègues à Kevin Chagnon"
The link "Inviter des mes collègues" should be changed to "Inviter mes collègues"

colleagues

### PR DESCRIPTION
**Pull request by kufii**
Contains:
Infinite Scroll on The Wire
Mandatory fields on groups
Fixes #811 #912 #536 #875

### CODE REVIEW

**Comment by smellems** [comment]
Could you create separate pull requests for each feature and fix?  Your fixes look interesting, but it will be easier to merge them if they are split up.

**Comment by kufii** [comment]
Sure, when I have some spare time I'll make separate PRs

**Comment by smellems** [comment]
I hope you kept your changes somewhere

**Comment by kufii** [comment]
Not too complicated to separate out the individual commits with git cherry-pick, been doing that

**Comment by Phanoix** [comment]
Thanks for splitting it up!

**Pull request closed without merging**
