### PR TITLE
Event import export to Outlook

### PR DESCRIPTION
**Pull request by iesfpiper**
# Added import/export functionality for events.

## Team Leeroy Jenkins
Francis Grignon
Li Wang
Pascal St-Denis
Stephen Arsenault

### Features:
- An outlook icon is added next to each event which when clicked generates an ICAL file which can be imported into outlook
- Supports both official languages
- Supports rich text format
- Supports batch export

### CODE REVIEW

**Comment by Steph4104** [comment]
error_ics

This is the error I have when I import a ICS file to my Outlook (The ics file is from gcconnex or one I create from Outlook)

**Comment by nschonni** [comment]
It looks like the first commit accidentally rebased/reverted a bunch of unrelated files.

**Comment by ToferC** [comment]
The problem with ics files is that many government agencies block them.
This then becomes an organizational security policy issue.

**Comment by Phanoix** [comment]
Closing this for now because of the issues described above, we can take a look at this again if those change.

**Comment by KingBain** [comment]
@Phanoix  Can this feature request be reopened? With the new emphasis on PANDU and #GCDigital departments are again allowing icals through the corporate firewall. I can say from experience that SSC is allowing Icals through.

TBS is using their gccollab site for #GCEARB events calendar and I actually need this integration for my work calendar; for work.

**Comment by iesfpiper** [comment]
> @Phanoix Can this feature request be reopened? With the new emphasis on PANDU and #GCDigital departments are again allowing icals through the corporate firewall. I can say from experience that SSC is allowing Icals through.
> 
> TBS is using their gccollab site for #GCEARB events calendar and I actually need this integration for my work calendar; for work.

I'll do some looking into this over the weekend and see if I can clean up this pull request.  I was fairly new to GIT when I was participating in the hackathon.

**Pull request closed without merging**
